### ISSUE TITLE
Invariant Violation: requireNativeComponent: "ARTShape" was not found in the UIManager.

### ISSUE THREAD

**Issue by cdesch** [react-native-community/art#46] opened 2019-12-17 18:19 UTC
# Bug

Running into `Invariant Violation: requireNativeComponent: "ARTShape" was not found in the UIManager.`

## Environment info
```
info Fetching system and libraries information...
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 2.49 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.3.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.1, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 20.1.5948944
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
```

React native info output:

Library version: 1.0.3

## Steps To Reproduce

1. After upgrading to react-native 0.61, the removal of the ART library required usage of the community library. 
2. Using the community library with this [barcode builder](https://github.com/wonsikin/react-native-barcode-builder) renders the error after changing the following as per the library:

Code:
```
import {ART} from 'react-native';
const {Surface, Shape} = ART;
```
to:
```
import {Surface, Shape} from '@react-native-community/art';
```

Related issue: https://github.com/wonsikin/react-native-barcode-builder/issues/49 

## Reproducible sample code

Link: https://github.com/wonsikin/react-native-barcode-builder/blob/529d87fc00a244ccf69ccd3e9716ab8c8a6def61/index.js#L174 

```
   <View style={[styles.svgContainer, backgroundStyle]}>
        <Surface height={this.props.height} width={this.state.barCodeWidth}>
          <Shape d={this.state.bars} fill={this.props.lineColor} />
        </Surface>
        { typeof(this.props.text) != 'undefined' &&
          <Text style={{color: this.props.textColor, width: this.state.barCodeWidth, textAlign: 'center'}} >{this.props.text}</Text>
        }
      </View>
```

## Error:
```
Invariant Violation: requireNativeComponent: "ARTShape" was not found in the UIManager.

This error is located at:
    in ARTShape (at Shape.js:58)
    in Shape (at Barcode.js:178)
    in ARTSurfaceView (at Surface.js:37)
    in Surface (at Barcode.js:177)
    in RCTView (at Barcode.js:176)
    in Barcode (at ProfileScreen/index.js:69)
    in RCTView (at CardItem.js:22)
    in CardItem (at connectStyle.js:392)
    in Styled(CardItem) (at ProfileScreen/index.js:68)
    in RCTView (at Card.js:21)
    in Card (at connectStyle.js:392)
    in Styled(Card) (at ProfileScreen/index.js:51)
    in RCTView (at View.js:10)
    in ViewNB (at connectStyle.js:392)
    in Styled(ViewNB) (at ProfileScreen/index.js:50)
    in RCTScrollContentView (at ScrollView.js:1038)
    in RCTScrollView (at ScrollView.js:1178)
    in ScrollView (at KeyboardAwareHOC.js:517)
    in KeyboardAwareScrollView (at Content.js:66)
    in Content (at connectStyle.js:392)
    in Styled(Content) (at ProfileScreen/index.js:49)
    in RCTView (at ImageBackground.js:60)
    in ImageBackground (at ProfileScreen/index.js:30)
    in RCTView (at Container.js:12)
    in Container (at connectStyle.js:392)
    in Styled(Container) (at ProfileScreen/index.js:29)
    in ProfileScreen (created by Connect(ProfileScreen))
    in Connect(ProfileScreen) (at SceneView.js:9)
    in SceneView (at DrawerView.js:149)
    in RCTView (at ResourceSavingScene.js:20)
    in RCTView (at ResourceSavingScene.js:16)
    in ResourceSavingScene (at DrawerView.js:148)
    in RCTView (at screens.native.js:83)
    in ScreenContainer (at DrawerView.js:138)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at DrawerLayout.js:446)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at DrawerLayout.js:445)
    in PanGestureHandler (at DrawerLayout.js:504)
    in DrawerLayout (at DrawerView.js:165)
    in DrawerView (at createNavigator.js:61)
    in Navigator (at SceneView.js:9)
    in SceneView (at StackViewLayout.tsx:899)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.tsx:93)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.tsx:80)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:971)
    in RCTView (at screens.native.js:83)
    in ScreenContainer (at StackViewLayout.tsx:383)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.tsx:379)
    in PanGestureHandler (at StackViewLayout.tsx:372)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.tsx:103)
    in RCTView (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:40)
    in StackView (at createNavigator.js:61)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at createAppContainer.js:429)
    in NavigationContainer (at App.tsx:205)
    in RCTView (at Root.js:14)
    in Root (at connectStyle.js:392)
    in Styled(Root) (at App.tsx:204)
    in RootContainer (created by Connect(RootContainer))
    in Connect(RootContainer) (at setup.js:48)
    in PersistGate (at setup.js:47)
    in Provider (at setup.js:46)
    in StyleProvider (at setup.js:45)
    in Setup (at App.js:21)
    in App (at withExpoRoot.js:26)
    in RootErrorBoundary (at withExpoRoot.js:25)
    in ExpoRoot (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in DevAppContainer (at AppContainer.js:115)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

getNativeComponentAttributes
    getNativeComponentAttributes.js:30:4
exports.get
    ReactNativeViewConfigRegistry.js:102:25
renderRoot
    [native code]:0
runRootCallback
    [native code]:0
unstable_runWithPriority
    scheduler.development.js:643:23
callFunctionReturnFlushedQueue
    [native code]:0

```

**Comment by Esemesek** [comment] 2019-12-18 15:11
It seems like you didn't link the library properly. This is not really an issue with this lib, but rather your configuration. I will be able to help you if you create some kind of reproducible demo. Closing this issue for now.

**Closed by Esemesek** 2019-12-18 15:11 UTC

**Comment by cdesch** [comment] 2019-12-18 17:17
Thanks @Esemesek. Here is the code: https://github.com/cdesch/barcode-test/tree/art-46 that reproduces the error. 

If you think that the library is not linking properly, do you think it could be because this is an Expo project? I ran into this issue after upgraded to Expo v36 from v35. In that upgrade ReactNative is upgraded `0.59.8 -> 0.61.4`, which deprecates the ART library from RN.

**Comment by Esemesek** [comment] 2019-12-18 17:22
You cannot link or add custom native dependencies to Expo without ejecting it. It seems like Expo removed it (https://github.com/expo/expo/issues/6482) in the latest SDK and this is the reason that `ART` is not working for you. I cannot really help you here as this is an issue with Expo integration.

**Comment by nmvictor** [comment] 2020-05-29 08:01
For iOS, adding this in Podfile helped:
`pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'`

**Comment by evgenButurlia** [comment] 2020-07-04 06:20
> For iOS, adding this in Podfile helped:
> `pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'`
> then had to run `pod install`

Actually this is the needed pod
pod 'ReactNativeART', :podspec => '../node_modules/@react-native-community/art/ReactNativeART.podspec'
@Esemesek seems like auto-linking does not work.
